### ISSUE TITLE
How can i import images?

### ISSUE THREAD

**Issue by steppo79** [pixelant/pxa_pm_importer#41]
Great extension, good job, thank you!

I try to import images with the importer.
For testing, I have taken the demo files, adapted Yaml and then imported.

Text comes into the database but no pictures. TYPO3 9.5.7 is in use.
The paths I have already adjusted, the pictures are unfortunately not accepted.

THX

**Comment by anjeylink** [comment]
in what fields are you importing?

**Comment by steppo79** [comment]
For testing, I use the original Ext. with the default settings.

**Comment by anjeylink** [comment]
@steppo79 import of images is working with proper configuration, so I'll close this issue
